spring:
  config:
    activate:
      on-profile: stg
  datasource:
    url: jdbc:mysql://localhost:3306/${stg_schema}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${stg_username}
    password: ${stg_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect